[gwrite.plotter]
# vertical_flip = true

document_start = '''
G90     ; absolute coordinates
G21     ; mm units
G17     ; xy plane
G00 Z5  ; up
'''

segment_first = '''
G00 X{x:.2f} Y{y:.2f}
G01 Z-1; down F300
'''

segment = '''
G01 X{x:.2f} Y{y:.2f} F2000
'''

segment_last = '''
G01 X{x:.2f} Y{y:.2f} F2000
G00 Z5  ; up
'''

document_end = '''
M2        ; program end
'''

unit = "mm"

# scale is (1 / (1/96 inch to mm)) -> 1px == 1mm
scale_x = 3.779527559
scale_y = 3.779527559