[gwrite.plotter]
invert_y = true

document_start = '''
G90     ; absolute coordinates
G21     ; mm units
G17     ; xy plane
G00 Z5  ; up
'''

segment_first = '''
G00 X{x:.2f} Y{y:.2f}
G01 Z-1 F999; down
'''

segment = '''
G01 X{x:.2f} Y{y:.2f} F2000
'''

segment_last = '''
G01 X{x:.2f} Y{y:.2f} F2000
G00 Z5  ; up
'''

document_end = '''
M2        ; program end
'''

unit = "mm"